openapi: 3.0.3
info:
  title: WhatsApp plantillas
  description: >-
    En esta sección abordaremos en envio de plantillas por api, es importante
    configurar tu canal de **WHATSAPP** para relizar estas peticiones.
  version: 1.0.0
  contact: {}
servers:
  - url: 'https://kservice.konnect-360.pe'
paths:
  /api/v1/whatsapp/templates:
    get:
      summary: Todas las plantillas
      description: Este endpoint es para obtener todas las plantillas disponibles.
      operationId: todasLasPlantillas
      responses:
        '200':
          description: Success
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Connection:
              schema:
                type: string
                example: keep-alive
            Content-Length:
              schema:
                type: string
                example: '2947'
            Date:
              schema:
                type: string
                example: Fri, 20 Jun 2025 03:45:48 GMT
            ETag:
              schema:
                type: string
                example: W/"b83-300vv6iugoJCV4nVcaw5uqjgHSo"
            Keep-Alive:
              schema:
                type: string
                example: timeout=5
            X-Powered-By:
              schema:
                type: string
                example: Express
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        category:
                          type: string
                          example: UTILITY
                        id:
                          type: string
                          example: '438429459276413'
                        language:
                          type: string
                          example: es
                        name:
                          type: string
                          example: salio_ruta
                        status:
                          type: string
                          example: APPROVED
                    example:
                      - category: UTILITY
                        id: '438429459276413'
                        language: es
                        name: salio_ruta
                        status: APPROVED
                      - category: UTILITY
                        id: '903530904852520'
                        language: es
                        name: template_name
                        status: APPROVED
                  errors:
                    type: object
                    properties: {}
                  messages:
                    type: string
                    example: OK
                  status:
                    type: number
                    example: 200
                  success:
                    type: boolean
                    example: true
              examples:
                Success:
                  value:
                    data:
                      - category: UTILITY
                        id: '438429459276413'
                        language: es
                        name: salio_ruta
                        status: APPROVED
                      - category: UTILITY
                        id: '903530904852520'
                        language: es
                        name: template_name
                        status: APPROVED
                    errors: {}
                    messages: OK
                    status: 200
                    success: true
      security:
        - bearerAuth: []
  /api/v1/whatsapp/template:
    get:
      summary: Plantilla por nombre
      description: Este end-point es para obtner una plantilla según el _**nombre**_
      operationId: plantillaPorNombre
      parameters:
        - name: name
          in: query
          schema:
            type: string
            example: salio_ruta
          description: string
      responses:
        '200':
          description: Success / Void
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Connection:
              schema:
                type: string
                example: keep-alive
            Content-Length:
              schema:
                type: string
                example: '133'
            Date:
              schema:
                type: string
                example: Fri, 20 Jun 2025 03:51:29 GMT
            ETag:
              schema:
                type: string
                example: W/"85-5mzYGnHkyyNQpEEr4uFv5p1OI+I"
            Keep-Alive:
              schema:
                type: string
                example: timeout=5
            X-Powered-By:
              schema:
                type: string
                example: Express
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 200
                  data:
                    type: object
                    properties:
                      category:
                        type: string
                        example: UTILITY
                      components:
                        type: array
                        items:
                          type: object
                          properties:
                            buttons:
                              type: array
                              items:
                                type: object
                                properties:
                                  example:
                                    type: array
                                    items:
                                      type: string
                                      example: >-
                                        https://www.urbano.com.pe/tracking?guides=WYB382992466
                                    example:
                                      - >-
                                        https://www.urbano.com.pe/tracking?guides=WYB382992466
                                  text:
                                    type: string
                                    example: Rastrea en nuestra web
                                  type:
                                    type: string
                                    example: URL
                                  url:
                                    type: string
                                    example: >-
                                      https://www.urbano.com.pe/tracking/?guides={{1}}
                              example:
                                - example:
                                    - >-
                                      https://www.urbano.com.pe/tracking?guides=WYB382992466
                                  text: Rastrea en nuestra web
                                  type: URL
                                  url: >-
                                    https://www.urbano.com.pe/tracking/?guides={{1}}
                            example:
                              type: object
                              properties:
                                body_text_named_params:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      example:
                                        type: string
                                        example: Victor Zuñiga
                                      param_name:
                                        type: string
                                        example: cliente_name
                                  example:
                                    - example: Victor Zuñiga
                                      param_name: cliente_name
                                    - example: Adidas
                                      param_name: shipper_name
                                    - example: APE9232323
                                      param_name: tracking
                                    - example: Av. Brasil 2050
                                      param_name: dir_delivery
                                    - example: Pueblo Libre
                                      param_name: ciudad
                            text:
                              type: string
                              example: >-
                                Hola {{cliente_name}}, somos urbano, encargado
                                de entregar tu pedido de {{shipper_name}}, tu
                                pedido con código de seguimiento {{tracking}} ya
                                esta en camino a tu dirección para su entrega,
                                por favor confirmarnos si tu dirección es la
                                correcta y si es posible envíanos  alguna
                                referencia y las coordenadas para que la entrega
                                sea efectiva, la dirección que registramos para
                                su entrega es {{dir_delivery}} distrito de
                                {{ciudad}}, nuestro personal encargado de la
                                entrega se estará acercando en el rango horario
                                de 8am a 6pm, estar pendiente de cualquier otra
                                comunicación.
                            type:
                              type: string
                              example: BODY
                        example:
                          - example:
                              body_text_named_params:
                                - example: Victor Zuñiga
                                  param_name: cliente_name
                                - example: Adidas
                                  param_name: shipper_name
                                - example: APE9232323
                                  param_name: tracking
                                - example: Av. Brasil 2050
                                  param_name: dir_delivery
                                - example: Pueblo Libre
                                  param_name: ciudad
                            text: >-
                              Hola {{cliente_name}}, somos urbano, encargado de
                              entregar tu pedido de {{shipper_name}}, tu pedido
                              con código de seguimiento {{tracking}} ya esta en
                              camino a tu dirección para su entrega, por favor
                              confirmarnos si tu dirección es la correcta y si
                              es posible envíanos  alguna referencia y las
                              coordenadas para que la entrega sea efectiva, la
                              dirección que registramos para su entrega es
                              {{dir_delivery}} distrito de {{ciudad}}, nuestro
                              personal encargado de la entrega se estará
                              acercando en el rango horario de 8am a 6pm, estar
                              pendiente de cualquier otra comunicación.
                            type: BODY
                          - text: Nos movemos por ti
                            type: FOOTER
                          - buttons:
                              - example:
                                  - >-
                                    https://www.urbano.com.pe/tracking?guides=WYB382992466
                                text: Rastrea en nuestra web
                                type: URL
                                url: >-
                                  https://www.urbano.com.pe/tracking/?guides={{1}}
                            type: BUTTONS
                      data:
                        type: array
                        items: {}
                        example: []
                      id:
                        type: string
                        example: '1331721198410285'
                      language:
                        type: string
                        example: es_PE
                      name:
                        type: string
                        example: salio_ruta
                      paging:
                        type: object
                        properties:
                          cursors:
                            type: object
                            properties:
                              after:
                                type: string
                                example: MjQZD
                              before:
                                type: string
                                example: MAZDZD
                      parameter_format:
                        type: string
                        example: NAMED
                      status:
                        type: string
                        example: APPROVED
                      sub_category:
                        type: string
                        example: CUSTOM
                  errors:
                    type: object
                    properties: {}
                  messages:
                    type: string
                    example: OK
                  status:
                    type: number
                    example: 200
                  success:
                    type: boolean
                    example: true
              examples:
                Success:
                  value:
                    code: 200
                    data:
                      category: UTILITY
                      components:
                        - example:
                            body_text_named_params:
                              - example: Victor Zuñiga
                                param_name: cliente_name
                              - example: Adidas
                                param_name: shipper_name
                              - example: APE9232323
                                param_name: tracking
                              - example: Av. Brasil 2050
                                param_name: dir_delivery
                              - example: Pueblo Libre
                                param_name: ciudad
                          text: >-
                            Hola {{cliente_name}}, somos urbano, encargado de
                            entregar tu pedido de {{shipper_name}}, tu pedido
                            con código de seguimiento {{tracking}} ya esta en
                            camino a tu dirección para su entrega, por favor
                            confirmarnos si tu dirección es la correcta y si es
                            posible envíanos  alguna referencia y las
                            coordenadas para que la entrega sea efectiva, la
                            dirección que registramos para su entrega es
                            {{dir_delivery}} distrito de {{ciudad}}, nuestro
                            personal encargado de la entrega se estará acercando
                            en el rango horario de 8am a 6pm, estar pendiente de
                            cualquier otra comunicación.
                          type: BODY
                        - text: Nos movemos por ti
                          type: FOOTER
                        - buttons:
                            - example:
                                - >-
                                  https://www.urbano.com.pe/tracking?guides=WYB382992466
                              text: Rastrea en nuestra web
                              type: URL
                              url: https://www.urbano.com.pe/tracking/?guides={{1}}
                          type: BUTTONS
                      id: '1331721198410285'
                      language: es_PE
                      name: salio_ruta
                      parameter_format: NAMED
                      status: APPROVED
                      sub_category: CUSTOM
                    errors: {}
                    messages: OK
                    status: 200
                    success: true
                Void:
                  value:
                    data:
                      data: []
                      paging:
                        cursors:
                          after: MjQZD
                          before: MAZDZD
                    errors: {}
                    messages: OK
                    status: 200
                    success: true
      security:
        - bearerAuth: []
  /api/v1/whatsapp/template-params:
    get:
      summary: Parametros de una plantilla
      description: >-
        Este end-point es para obtener los parametros de una plantilla por su
        _**nombre**_
      operationId: parametrosDeUnaPlantilla
      parameters:
        - name: name
          in: query
          schema:
            type: string
            example: salio_ruta
          description: string
      responses:
        '200':
          description: Success
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Connection:
              schema:
                type: string
                example: keep-alive
            Content-Length:
              schema:
                type: string
                example: '258'
            Date:
              schema:
                type: string
                example: Fri, 20 Jun 2025 03:52:43 GMT
            ETag:
              schema:
                type: string
                example: W/"102-romVwDaNyZpXrIFXmrD/sZ6cRrg"
            Keep-Alive:
              schema:
                type: string
                example: timeout=5
            X-Powered-By:
              schema:
                type: string
                example: Express
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 200
                  data:
                    type: object
                    properties:
                      template_body:
                        type: array
                        items:
                          type: object
                          properties:
                            index:
                              type: number
                              example: 0
                            parameters:
                              type: array
                              items:
                                type: object
                                properties:
                                  parameter_name:
                                    type: string
                                    example: cliente_name
                                  text:
                                    type: string
                                    example: ''
                                  type:
                                    type: string
                                    example: text
                              example:
                                - parameter_name: cliente_name
                                  text: ''
                                  type: text
                                - parameter_name: shipper_name
                                  text: ''
                                  type: text
                                - parameter_name: tracking
                                  text: ''
                                  type: text
                                - parameter_name: dir_delivery
                                  text: ''
                                  type: text
                                - parameter_name: ciudad
                                  text: ''
                                  type: text
                            sub_type:
                              type: string
                              example: url
                            type:
                              type: string
                              example: body
                        example:
                          - parameters:
                              - parameter_name: cliente_name
                                text: ''
                                type: text
                              - parameter_name: shipper_name
                                text: ''
                                type: text
                              - parameter_name: tracking
                                text: ''
                                type: text
                              - parameter_name: dir_delivery
                                text: ''
                                type: text
                              - parameter_name: ciudad
                                text: ''
                                type: text
                            type: body
                          - index: 0
                            parameters:
                              - text: ''
                                type: text
                            sub_type: url
                            type: button
                      template_name:
                        type: string
                        example: salio_ruta
                  errors:
                    type: object
                    properties: {}
                  messages:
                    type: string
                    example: OK
                  status:
                    type: number
                    example: 200
                  success:
                    type: boolean
                    example: true
              examples:
                Success:
                  value:
                    code: 200
                    data:
                      template_body:
                        - parameters:
                            - parameter_name: cliente_name
                              text: ''
                              type: text
                            - parameter_name: shipper_name
                              text: ''
                              type: text
                            - parameter_name: tracking
                              text: ''
                              type: text
                            - parameter_name: dir_delivery
                              text: ''
                              type: text
                            - parameter_name: ciudad
                              text: ''
                              type: text
                          type: body
                        - index: 0
                          parameters:
                            - text: ''
                              type: text
                          sub_type: url
                          type: button
                      template_name: salio_ruta
                    errors: {}
                    messages: OK
                    status: 200
                    success: true
        '400':
          description: Error
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Connection:
              schema:
                type: string
                example: keep-alive
            Content-Length:
              schema:
                type: string
                example: '95'
            Date:
              schema:
                type: string
                example: Fri, 20 Jun 2025 03:53:49 GMT
            ETag:
              schema:
                type: string
                example: W/"5f-Lzfx7/4qN6fr20Ky0tUbbhpRN9s"
            Keep-Alive:
              schema:
                type: string
                example: timeout=5
            X-Powered-By:
              schema:
                type: string
                example: Express
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 200
                  data:
                    nullable: true
                    example: null
                  errors:
                    type: object
                    properties: {}
                  messages:
                    type: string
                    example: Opps plantilla no encontrada
                  status:
                    type: number
                    example: 400
                  success:
                    type: boolean
                    example: true
              examples:
                Error:
                  value:
                    code: 200
                    data: null
                    errors: {}
                    messages: Opps plantilla no encontrada
                    status: 400
                    success: true
      security:
        - bearerAuth: []
  /api/v1/whatsapp/send-template:
    post:
      summary: Enviar plantilla
      description: >-
        Este end-point es para enviar una _**plantilla con parametros**_ vacios
        y sus respectivos valores ordenados
      operationId: enviarPlantilla
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                template_body:
                  type: array
                  items:
                    type: object
                    properties:
                      index:
                        type: number
                        example: 0
                      parameters:
                        type: array
                        items:
                          type: object
                          properties:
                            parameter_name:
                              type: string
                              example: cliente_name
                            text:
                              type: string
                              example: Rodrigo
                            type:
                              type: string
                              example: text
                        example:
                          - parameter_name: cliente_name
                            text: Rodrigo
                            type: text
                          - parameter_name: shipper_name
                            text: SKYPOSTAL SAC
                            type: text
                          - parameter_name: tracking
                            text: '3344555'
                            type: text
                          - parameter_name: dir_delivery
                            text: 'JR Example #22'
                            type: text
                          - parameter_name: ciudad
                            text: Lima
                            type: text
                      sub_type:
                        type: string
                        example: url
                      type:
                        type: string
                        example: body
                  example:
                    - parameters:
                        - parameter_name: cliente_name
                          text: Rodrigo
                          type: text
                        - parameter_name: shipper_name
                          text: SKYPOSTAL SAC
                          type: text
                        - parameter_name: tracking
                          text: '3344555'
                          type: text
                        - parameter_name: dir_delivery
                          text: 'JR Example #22'
                          type: text
                        - parameter_name: ciudad
                          text: Lima
                          type: text
                      type: body
                    - index: 0
                      parameters:
                        - text: Wyb123123
                          type: text
                      sub_type: url
                      type: button
                template_name:
                  type: string
                  example: salio_ruta
                to_phone_number:
                  type: string
                  example: '{{phone}}'
                to_url_tracking:
                  type: string
                  example: ''
                tracking_number:
                  type: string
                  example: '12333322'
            examples:
              Enviar plantilla:
                value:
                  template_body:
                    - parameters:
                        - parameter_name: cliente_name
                          text: Rodrigo
                          type: text
                        - parameter_name: shipper_name
                          text: SKYPOSTAL SAC
                          type: text
                        - parameter_name: tracking
                          text: '3344555'
                          type: text
                        - parameter_name: dir_delivery
                          text: 'JR Example #22'
                          type: text
                        - parameter_name: ciudad
                          text: Lima
                          type: text
                      type: body
                    - index: 0
                      parameters:
                        - text: Wyb123123
                          type: text
                      sub_type: url
                      type: button
                  template_name: salio_ruta
                  to_phone_number: '{{phone}}'
                  to_url_tracking: ''
                  tracking_number: '12333322'
      responses:
        '200':
          description: Success
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Connection:
              schema:
                type: string
                example: keep-alive
            Content-Length:
              schema:
                type: string
                example: '196'
            Date:
              schema:
                type: string
                example: Fri, 20 Jun 2025 03:58:58 GMT
            ETag:
              schema:
                type: string
                example: W/"c4-BUd/Sa8jdVSPvKYhK9FgLlCge+c"
            Keep-Alive:
              schema:
                type: string
                example: timeout=5
            X-Powered-By:
              schema:
                type: string
                example: Express
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      channel:
                        type: string
                        example: whatsapp
                      messages:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                              example: >-
                                wamid.HBgLNTE5MDY1ODk3NjAVAgARGBJFRTBBMTc5N0ExRTIzOTE4NDgA
                            message_status:
                              type: string
                              example: accepted
                        example:
                          - id: >-
                              wamid.HBgLNTE5MDY1ODk3NjAVAgARGBJFRTBBMTc5N0ExRTIzOTE4NDgA
                            message_status: accepted
                  errors:
                    type: object
                    properties: {}
                  messages:
                    type: string
                    example: OK
                  status:
                    type: number
                    example: 200
                  success:
                    type: boolean
                    example: true
              examples:
                Success:
                  value:
                    data:
                      channel: whatsapp
                      messages:
                        - id: >-
                            wamid.HBgLNTE5MDY1ODk3NjAVAgARGBJFRTBBMTc5N0ExRTIzOTE4NDgA
                          message_status: accepted
                    errors: {}
                    messages: OK
                    status: 200
                    success: true
        '400':
          description: Error
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Connection:
              schema:
                type: string
                example: keep-alive
            Content-Length:
              schema:
                type: string
                example: '351'
            Date:
              schema:
                type: string
                example: Fri, 20 Jun 2025 03:58:04 GMT
            ETag:
              schema:
                type: string
                example: W/"15f-d/3WeWzQ7Amehqj+x1m2A7Jo+Pk"
            Keep-Alive:
              schema:
                type: string
                example: timeout=5
            X-Powered-By:
              schema:
                type: string
                example: Express
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    nullable: true
                    example: null
                  errors:
                    type: object
                    properties:
                      data:
                        type: object
                        properties:
                          details:
                            type: string
                            example: >-
                              body: number of localizable_params (4) does not
                              match the expected number of params (7)
                          messaging_product:
                            type: string
                            example: whatsapp
                      message:
                        type: string
                        example: >-
                          (#132000) Number of parameters does not match the
                          expected number of params
                      type:
                        type: string
                        example: OAuthException
                  messages:
                    type: string
                    example: Error en parametros de plantilla
                  status:
                    type: number
                    example: 400
                  success:
                    type: boolean
                    example: false
              examples:
                Error:
                  value:
                    data: null
                    errors:
                      data:
                        details: >-
                          body: number of localizable_params (4) does not match
                          the expected number of params (7)
                        messaging_product: whatsapp
                      message: >-
                        (#132000) Number of parameters does not match the
                        expected number of params
                      type: OAuthException
                    messages: Error en parametros de plantilla
                    status: 400
                    success: false
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags: []

